import 'issue_priority.dart';
import 'root_cause.dart';

/// Statement type classification for AI diagnosis content.
enum AiStatementType {
  fact,
  inference,
  recommendation,
}

/// A statement in AI diagnosis with statement type classification.
class AiStatement {
  const AiStatement({
    required this.text,
    required this.type,
    this.isSupported = true,
  });

  final String text;
  final AiStatementType type;
  final bool isSupported;
}

/// A recommendation generated by AI based on deterministic evidence.
class Recommendation {
  const Recommendation({
    required this.title,
    required this.explanation,
    required this.priority,
    this.relatedRootCause,
    this.isSupported = true,
    this.rejectionReason,
  });

  final String title;
  final String explanation;
  final IssuePriority priority;
  final String? relatedRootCause;
  final bool isSupported;
  final String? rejectionReason;
}

/// An AI-generated diagnosis for a specific root cause after consistency validation.
class RootCauseDiagnosis {
  const RootCauseDiagnosis({
    required this.title,
    required this.explanation,
    required this.priority,
    required this.deterministicConfidence,
    required this.aiConfidence,
    required this.evidence,
    required this.recommendedActions,
    required this.affectedFiles,
    required this.occurrenceCount,
    this.isSupported = true,
  });

  final String title;
  final String explanation;
  final IssuePriority priority;
  final RootCauseConfidence deterministicConfidence;
  final RootCauseConfidence aiConfidence;
  final List<String> evidence;
  final List<String> recommendedActions;
  final List<String> affectedFiles;
  final int occurrenceCount;
  final bool isSupported;
}

/// Comprehensive AI Diagnosis object after evidence consistency validation.
class AiDiagnosis {
  const AiDiagnosis({
    required this.summary,
    required this.healthAssessment,
    required this.rootCauses,
    required this.recommendations,
    required this.unsupportedRecommendations,
    required this.environmentAssessment,
    required this.confidence,
    required this.verifiedFacts,
    required this.claimsAcceptedCount,
    required this.claimsRejectedCount,
    required this.unsupportedClaimsCount,
  });

  final String summary;
  final String healthAssessment;
  final List<RootCauseDiagnosis> rootCauses;
  final List<Recommendation> recommendations;
  final List<Recommendation> unsupportedRecommendations;
  final String environmentAssessment;
  final RootCauseConfidence confidence;
  final Map<String, String> verifiedFacts;
  final int claimsAcceptedCount;
  final int claimsRejectedCount;
  final int unsupportedClaimsCount;
}

/// Structured execution result from [AiDiagnosisService].
class AiDiagnosisResult {
  const AiDiagnosisResult._({
    required this.isAvailable,
    this.diagnosis,
    this.unavailableReason,
  });

  factory AiDiagnosisResult.success(AiDiagnosis diagnosis) =>
      AiDiagnosisResult._(isAvailable: true, diagnosis: diagnosis);

  factory AiDiagnosisResult.unavailable(String reason) =>
      AiDiagnosisResult._(isAvailable: false, unavailableReason: reason);

  final bool isAvailable;
  final AiDiagnosis? diagnosis;
  final String? unavailableReason;
}
